package recipehaoling;

import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.AbstractListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import oracle.jdbc.OraclePreparedStatement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecipeFrame
     */
    //create database handler instance
    DatabaseHandler dbHandler = new DatabaseHandler();
    private DefaultListModel model;
    private DefaultListModel fridgeModel;
    private DefaultListModel ingredientsModel;
    private DefaultListModel shoppingListModel;
   
    
    //Variables
    private ArrayList<Ingredient> newIngredients = new ArrayList<>();  
    Recipe[] foundRecipes;

       
    public RecipeFrame() {
        initComponents();
        //initialize and display the date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");
	LocalDateTime now = LocalDateTime.now();
        dateTextView.setText(dtf.format(now));
        
        //frame set in center, do not change the size of the screen
        setLocationRelativeTo(null);
        setResizable(false);
	
        //hide search results view until there is an actual set of results to display
        searchResultsPane.setVisible(false);
        //this code will be use to modify what is displayed in the fridge, method needs to be created to generate fridge items
        fridgeListView.setText("Display fridge items, list nutrition facts.");
        //this will display the generated shopping list
        shoppingListView.setText("generate the shopping list here.");
        //this is the recipe list view in the planner tab, have client to check the boxes
        //that they wish to have a recipe to be entered at the checked time period
        
        //define model as new list.
            model = new DefaultListModel();
            //set list to final for access, and add list items to the list for user selection.
            //final JList list = new JList();
            Recipe[] currentRecipes = DatabaseHandler.getRecipes();
            //String[] values = new String[] {"Pizza", "MashedPotatoes", "Chicken", "Ramen noodles", "Guano", "Hot Hoggies", "Toaster Stroodle"};
            for(int i = 0; i < currentRecipes.length; i++){
                model.addElement(currentRecipes[i].getName());
            }
            jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mealsGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        recipeSearchText = new javax.swing.JTextField();
        SearchGo = new javax.swing.JButton();
        ManagerSheet = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fridgeListView = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        shoppingListView = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mealPlanShoppingList = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DayOfWeekDropMenu = new javax.swing.JComboBox<String>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        recipeSelectionListView = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jPanel5 = new javax.swing.JPanel();
        breakfastPlannerCheckbox = new javax.swing.JCheckBox();
        lunchPlannerCheckbox = new javax.swing.JCheckBox();
        dinnerPlannerCheckbox = new javax.swing.JCheckBox();
        breakfastPlannerTextView = new javax.swing.JTextField();
        lunchPlannerTextView = new javax.swing.JTextField();
        dinnerPlannerTextView = new javax.swing.JTextField();
        clearPlanner = new javax.swing.JButton();
        StoreButton = new javax.swing.JButton();
        moveFromList = new javax.swing.JButton();
        weekID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        radioBreakfast = new javax.swing.JRadioButton();
        radioLunch = new javax.swing.JRadioButton();
        radioDinner = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        daysBox = new javax.swing.JComboBox<String>();
        applyButton = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        recipeList = new javax.swing.JList<String>();
        jScrollPane3 = new javax.swing.JScrollPane();
        recipeInstruc = new javax.swing.JTextArea();
        weekId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addRecipePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addRecipeName = new javax.swing.JTextField();
        InstructionsLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        addRecipeInstructions = new javax.swing.JTextArea();
        storeRecipe = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        addRecipeCategory = new javax.swing.JTextField();
        ingredientName = new javax.swing.JTextField();
        ingredientCal = new javax.swing.JTextField();
        ingredientFat = new javax.swing.JTextField();
        ingredientSodium = new javax.swing.JTextField();
        ingredientGroup = new javax.swing.JTextField();
        ingredientSugar = new javax.swing.JTextField();
        ingredientProtein = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ingredientFatlab = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ingredientProteinlab = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        addIngredient = new javax.swing.JButton();
        searchResultsPane = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        searchResultList = new javax.swing.JList<String>();
        dateLabel = new javax.swing.JLabel();
        dateTextView = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        debugArea = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemLoad = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Search Recipe Category");
        jLabel1.setToolTipText("");

        recipeSearchText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        SearchGo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SearchGo.setText("Go");
        SearchGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchGoActionPerformed(evt);
            }
        });

        fridgeListView.setEditable(false);
        fridgeListView.setColumns(20);
        fridgeListView.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fridgeListView.setRows(5);
        jScrollPane1.setViewportView(fridgeListView);

        shoppingListView.setColumns(20);
        shoppingListView.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        shoppingListView.setRows(5);
        jScrollPane2.setViewportView(shoppingListView);

        jLabel2.setText("The Fridge");

        jLabel3.setText("The Shopping List");

        jLabel9.setText("Meal Plan Name:");

        mealPlanShoppingList.setText("jTextField1");

        jButton1.setText("Generate");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(251, 251, 251)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mealPlanShoppingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(jButton1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mealPlanShoppingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ManagerSheet.addTab("Fridge", jPanel1);

        DayOfWeekDropMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DayOfWeekDropMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wensday", "Thursday", "Friday", "Saturday", "Sunday" }));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Recipe Selection List");
        jLabel5.setToolTipText("");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        recipeSelectionListView.setViewportView(jList1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(recipeSelectionListView)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(recipeSelectionListView, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
        );

        breakfastPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        breakfastPlannerCheckbox.setText("Breakfast");
        breakfastPlannerCheckbox.setToolTipText("");

        lunchPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lunchPlannerCheckbox.setText("Lunch");
        lunchPlannerCheckbox.setToolTipText("");

        dinnerPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dinnerPlannerCheckbox.setText("Dinner");
        dinnerPlannerCheckbox.setToolTipText("");

        clearPlanner.setText("Clear");
        clearPlanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPlannerActionPerformed(evt);
            }
        });

        StoreButton.setText("Store");
        StoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clearPlanner)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(breakfastPlannerCheckbox)
                        .addComponent(lunchPlannerCheckbox)
                        .addComponent(dinnerPlannerCheckbox)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breakfastPlannerTextView, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(lunchPlannerTextView)
                            .addComponent(dinnerPlannerTextView))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(StoreButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfastPlannerCheckbox)
                    .addComponent(breakfastPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchPlannerCheckbox)
                    .addComponent(lunchPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinnerPlannerCheckbox)
                    .addComponent(dinnerPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearPlanner)
                    .addComponent(StoreButton))
                .addContainerGap())
        );

        moveFromList.setText(">>");
        moveFromList.setToolTipText("");
        moveFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveFromListActionPerformed(evt);
            }
        });

        weekID.setText("Please Enter a name");

        jLabel8.setText("Meal Plan Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveFromList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(weekID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DayOfWeekDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DayOfWeekDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(moveFromList)
                            .addComponent(weekID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        ManagerSheet.addTab("Planner", jPanel2);

        mealsGroup.add(radioBreakfast);
        radioBreakfast.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioBreakfast.setText("Breakfast");
        radioBreakfast.setToolTipText("");
        radioBreakfast.setActionCommand("radioBreakfast");
        radioBreakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBreakfastActionPerformed(evt);
            }
        });

        mealsGroup.add(radioLunch);
        radioLunch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioLunch.setText("Lunch");
        radioLunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLunchActionPerformed(evt);
            }
        });

        mealsGroup.add(radioDinner);
        radioDinner.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioDinner.setText("Dinner");
        radioDinner.setToolTipText("");
        radioDinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinnerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Meal Plan");
        jLabel4.setToolTipText("");

        daysBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        daysBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        applyButton.setText("Apply");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });

        recipeList.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        recipeList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recipeListMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(recipeList);

        recipeInstruc.setColumns(20);
        recipeInstruc.setRows(5);
        jScrollPane3.setViewportView(recipeInstruc);

        jLabel10.setText("Meal Plan Name");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(weekId, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(radioBreakfast)
                                .addGap(18, 18, 18)
                                .addComponent(radioLunch)
                                .addGap(18, 18, 18)
                                .addComponent(radioDinner)))
                        .addGap(18, 18, 18)
                        .addComponent(daysBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(applyButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daysBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioDinner)
                    .addComponent(radioLunch)
                    .addComponent(radioBreakfast)
                    .addComponent(weekId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(applyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                .addContainerGap())
        );

        ManagerSheet.addTab("Meal Plan", jPanel3);

        addRecipePanel.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Recipe Name");
        jLabel6.setToolTipText("");

        InstructionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InstructionsLabel.setText("Instructions");
        InstructionsLabel.setToolTipText("");

        addRecipeInstructions.setColumns(20);
        addRecipeInstructions.setRows(5);
        jScrollPane6.setViewportView(addRecipeInstructions);

        storeRecipe.setText("Store");
        storeRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeRecipeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Category");
        jLabel14.setToolTipText("");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Ingredients");
        jLabel15.setToolTipText("");

        ingredientName.setMinimumSize(new java.awt.Dimension(59, 20));
        ingredientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientNameActionPerformed(evt);
            }
        });

        ingredientCal.setMinimumSize(new java.awt.Dimension(59, 20));

        ingredientFat.setMinimumSize(new java.awt.Dimension(59, 20));

        ingredientSodium.setMinimumSize(new java.awt.Dimension(59, 20));

        ingredientGroup.setMinimumSize(new java.awt.Dimension(59, 20));

        ingredientSugar.setMinimumSize(new java.awt.Dimension(59, 20));

        ingredientProtein.setMinimumSize(new java.awt.Dimension(59, 20));

        jLabel16.setText("Name");

        jLabel17.setText("Calories");

        jLabel18.setText("Sodium");

        ingredientFatlab.setText("Fat");

        jLabel20.setText("Group");

        ingredientProteinlab.setText("Protein");

        jLabel22.setText("Sugar");

        addIngredient.setText("Add");
        addIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addRecipePanelLayout = new javax.swing.GroupLayout(addRecipePanel);
        addRecipePanel.setLayout(addRecipePanelLayout);
        addRecipePanelLayout.setHorizontalGroup(
            addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRecipePanelLayout.createSequentialGroup()
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel6))
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel15))
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel14))
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(addRecipeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRecipePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
            .addGroup(addRecipePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(storeRecipe)
                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(addRecipePanelLayout.createSequentialGroup()
                            .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(ingredientName, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(ingredientCal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ingredientFatlab)
                                .addComponent(ingredientFat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(InstructionsLabel)
                                .addGroup(addRecipePanelLayout.createSequentialGroup()
                                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(ingredientSodium, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(ingredientGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ingredientProteinlab)
                                        .addComponent(ingredientProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel22)
                                        .addComponent(ingredientSugar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(addIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        addRecipePanelLayout.setVerticalGroup(
            addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRecipePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addRecipeCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel15)
                .addGap(19, 19, 19)
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(ingredientFatlab)
                    .addComponent(jLabel20)
                    .addComponent(ingredientProteinlab)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingredientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingredientCal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientSodium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientSugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addIngredient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(InstructionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeRecipe)
                .addGap(28, 28, 28))
        );

        ManagerSheet.addTab("Add Recipe", addRecipePanel);

        jScrollPane5.setViewportView(searchResultList);

        javax.swing.GroupLayout searchResultsPaneLayout = new javax.swing.GroupLayout(searchResultsPane);
        searchResultsPane.setLayout(searchResultsPaneLayout);
        searchResultsPaneLayout.setHorizontalGroup(
            searchResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );
        searchResultsPaneLayout.setVerticalGroup(
            searchResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchResultsPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dateLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateLabel.setText("Today:");
        dateLabel.setToolTipText("");

        dateTextView.setEditable(false);
        dateTextView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateTextView.setToolTipText("");

        debugArea.setColumns(20);
        debugArea.setRows(5);
        jScrollPane7.setViewportView(debugArea);

        jLabel7.setText("Debugging area:");

        jMenu1.setText("File");

        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSave);

        menuItemLoad.setText("Load");
        menuItemLoad.setToolTipText("");
        menuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemLoad);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManagerSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 276, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchResultsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(recipeSearchText, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                        .addGap(2, 2, 2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(dateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SearchGo)
                                    .addComponent(dateTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ManagerSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SearchGo, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                            .addComponent(recipeSearchText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        ManagerSheet.getAccessibleContext().setAccessibleName("Fridge");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /*TALK WITH BRIAN ABOUT VARIABLE NAME ERRORS
    private void inititializeFridgeTab() {
        
        ingredientsModel = new DefaultListModel();
        fridgeModel = new DefaultListModel();
        
        shoppingLabel.setText("Ingredients List");
        //get ingredients in database
        Ingredient[] currentIngredients = DatabaseHandler.getIngredients();
        String[] values = new String[] {"Pizza", "MashedPotatoes", "Chicken", "Ramen noodles", "Guano", "Hot Hoggies", "Toaster Stroodle"};
        //add ingredients to the model list
        for(int i = 0; i < values.length; i++){
            ingredientsModel.addElement(values[i]);//currentIngredients[i].getName()
        }
        //set the list view to the ingredients model list
        shoppingListView.setModel(ingredientsModel);
        
        //build fridge
        
    }
    */
    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLoadActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // exit the program when selected
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void clearPlannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPlannerActionPerformed
        // TODO add your handling code here:
        breakfastPlannerTextView.setText("");
        lunchPlannerTextView.setText("");
        dinnerPlannerTextView.setText("");
    }//GEN-LAST:event_clearPlannerActionPerformed

    private void DayOfWeekDropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayOfWeekDropMenuActionPerformed
        // TODO add your handling code here:
        if(DayOfWeekDropMenu.hasFocus() == true) {
            breakfastPlannerTextView.setText("");
            lunchPlannerTextView.setText("");
            dinnerPlannerTextView.setText("");
        }
    }//GEN-LAST:event_DayOfWeekDropMenuActionPerformed
     private void searchActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        ArrayList recipeSearchList = new ArrayList();
        //collect recipe objects
        recipeSearchList.add(DatabaseHandler.searchRecipes(recipeSearchText.getText()));
        
        //model = new ListModel();
        
        //get each element and add to the model
        for(int i = 0; i < recipeSearchList.size(); i++){
            Recipe rec = (Recipe) recipeSearchList.get(i);
            String str = rec.getName();
            //model.add(str);
        }
        
        //then get collection, add model to the list
        jList1.setModel(model);
        //allow user to see search results
        searchResultsPane.setVisible(true);
        
        //at this point we may need to consider, that the user might want to select an item from the search list
    }   
        //this method is going to add ingredients to an array of ingredients
    private void addIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientActionPerformed
        // TODO add your handling code here:
        
        //define all the variables
        String ingredientN,ingredientG;
        int ingredientC, ingredientF, ingredientS,ingredientP, ingredientSug;
        ingredientN = ingredientName.getText();
        ingredientC = Integer.parseInt(ingredientCal.getText());
        ingredientF = Integer.parseInt(ingredientFat.getText());
        ingredientS = Integer.parseInt(ingredientSodium.getText());
        ingredientG = ingredientGroup.getText();
        ingredientP = Integer.parseInt(ingredientProtein.getText());
        ingredientSug = Integer.parseInt(ingredientSugar.getText());

        //create a new ingredient object
        Ingredient ingredient = new Ingredient(ingredientN, ingredientC, ingredientF, ingredientS, ingredientG, ingredientP, ingredientSug);
        DatabaseHandler.insertIngredient(ingredient);
        //add the object into ingredient list
        newIngredients.add(ingredient);

        //show a message showing the adding is succeeded
        JOptionPane.showMessageDialog(null, ingredientName.getText() + " is added!");
        
        //Debug Code!!! Delete it in Final Code
        debugArea.setText(debugArea.getText() + "\n" + ingredientName.getText()+ " contains: " + ingredientCal.getText() + " calories!");

        //clear the textfield for entering new ingredients
        ingredientName.setText("");
        ingredientCal.setText("");
        ingredientFat.setText("");
        ingredientSodium.setText("");
        ingredientGroup.setText("");
        ingredientProtein.setText("");
        ingredientSugar.setText("");

    }//GEN-LAST:event_addIngredientActionPerformed

    private void ingredientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingredientNameActionPerformed

    //this method will store new recipe into table
    private void storeRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeRecipeActionPerformed
        // TODO add your handling code here:
       
        String recipeCat, instructions, recipeName;
        recipeCat = addRecipeCategory.getText();
        instructions = addRecipeInstructions.getText();
        recipeName = addRecipeName.getText();

        //changing list to array
        Ingredient[] addedIngredients = new Ingredient[newIngredients.size()];
        for(int i = 0; i<newIngredients.size();i++){
            addedIngredients[i]=newIngredients.get(i);
        }
        //New recipe
        Recipe recipe = new Recipe(recipeCat, instructions, recipeName);
        try {
            DatabaseHandler.addRecipe(recipe, addedIngredients);
        } catch (InterruptedException ex) {
           //do nothing
        }
        addRecipeCategory.setText("");
        addRecipeInstructions.setText("");
        addRecipeName.setText("");
        //add refresh method call here
    }//GEN-LAST:event_storeRecipeActionPerformed

    private void radioDinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDinnerActionPerformed

    private void radioLunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLunchActionPerformed

    private void radioBreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBreakfastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBreakfastActionPerformed

    private void recipeListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recipeListMouseClicked
        String selectedRecipeName = recipeList.getSelectedValue();
        for(Recipe r : foundRecipes){
            if(r.getName().equals(selectedRecipeName)){
                recipeInstruc.setText(r.getInstruction());
            }
        }
    }//GEN-LAST:event_recipeListMouseClicked


    private void moveFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveFromListActionPerformed
        // TODO add your handling code here:
        // test cases for checkbox selections
        if(breakfastPlannerCheckbox.isSelected() && lunchPlannerCheckbox.isSelected() && dinnerPlannerCheckbox.isSelected()){
            breakfastPlannerTextView.setText(jList1.getSelectedValue());
            lunchPlannerTextView.setText(jList1.getSelectedValue());
            dinnerPlannerTextView.setText(jList1.getSelectedValue());
        }  else if(breakfastPlannerCheckbox.isSelected()){
            if(lunchPlannerCheckbox.isSelected()){
                breakfastPlannerTextView.setText(jList1.getSelectedValue());
                lunchPlannerTextView.setText(jList1.getSelectedValue());
            } else if(dinnerPlannerCheckbox.isSelected()) {
                breakfastPlannerTextView.setText(jList1.getSelectedValue());
                dinnerPlannerTextView.setText(jList1.getSelectedValue());
            } else {
                breakfastPlannerTextView.setText(jList1.getSelectedValue());
            }
        } else {
            if(lunchPlannerCheckbox.isSelected()) {
                if(dinnerPlannerCheckbox.isSelected()){
                    lunchPlannerTextView.setText(jList1.getSelectedValue());
                    dinnerPlannerTextView.setText(jList1.getSelectedValue());
                } else {
                    lunchPlannerTextView.setText(jList1.getSelectedValue());
                }
            } else if(dinnerPlannerCheckbox.isSelected()){
                dinnerPlannerTextView.setText(jList1.getSelectedValue());
            } else {
                //do nothing, could add tip here, no items selected.
            }
        }

    }//GEN-LAST:event_moveFromListActionPerformed

    private void StoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StoreButtonActionPerformed
        // TODO add your handling code here:
        //store
        // test cases for checkbox selections
        String Day = (String) DayOfWeekDropMenu.getSelectedItem();
        String mealplanName = weekID.getText();
        if(breakfastPlannerCheckbox.isSelected() && lunchPlannerCheckbox.isSelected() && dinnerPlannerCheckbox.isSelected()){
            Recipe breakfast = new Recipe(breakfastPlannerTextView.getText());            
            Recipe lunch = new Recipe(lunchPlannerTextView.getText());
            Recipe dinner = new Recipe(dinnerPlannerTextView.getText());
            DatabaseHandler.getRecipeID(breakfast);
            DatabaseHandler.getRecipeID(lunch);
            DatabaseHandler.getRecipeID(dinner);
            MealPlan BreakfastPlan = new MealPlan(mealplanName,"Breakfast",Day);
            MealPlan LunchPlan = new MealPlan(mealplanName,"Lunch",Day);
            MealPlan DinnerPlan = new MealPlan(mealplanName,"Dinner",Day);
            DatabaseHandler.addMealPlan(BreakfastPlan, breakfast);
            DatabaseHandler.addMealPlan(LunchPlan, lunch);
            DatabaseHandler.addMealPlan(DinnerPlan, dinner);
            
            
        }  else if(breakfastPlannerCheckbox.isSelected()){
            if(lunchPlannerCheckbox.isSelected()){
                breakfastPlannerTextView.getText();
                lunchPlannerTextView.getText();
            } else if(dinnerPlannerCheckbox.isSelected()) {
                breakfastPlannerTextView.getText();
                dinnerPlannerTextView.getText();
            } else {
                breakfastPlannerTextView.getText();
            }
        } else {
            if(lunchPlannerCheckbox.isSelected()) {
                if(dinnerPlannerCheckbox.isSelected()){
                    lunchPlannerTextView.getText();
                    dinnerPlannerTextView.getText();
                } else {
                    lunchPlannerTextView.getText();
                }
            } else if(dinnerPlannerCheckbox.isSelected()){
                dinnerPlannerTextView.getText();
            } else {
                //do nothing
            }
        }
    }//GEN-LAST:event_StoreButtonActionPerformed
  
    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        String selectedDay = daysBox.getActionCommand();
        String selectedMeal = mealsGroup.getSelection().getActionCommand();
        String selectedWeekId = weekId.getText();
        //MealPlan selectedMealPlan = new MealPlan(selectedWeekId,selectedMeal, selectedDay);
        //foundRecipes = DatabaseHandler.searchMealPlans(selectedMealPlan);
        DefaultListModel listModel = new DefaultListModel();
        for(Recipe r : foundRecipes){
            listModel.addElement(r.getName());
        }
      
        recipeList.setModel(listModel);
    }//GEN-LAST:event_applyButtonActionPerformed
    /*
    
    TODO TALK WITH BRIAN ABOUT VARIABLE NAME ERRORS
    
    private void addToFridgebtnActionPerformed(java.awt.event.ActionEvent evt) {                                               

        //add selected ingredient value and add to fridge list model
        
        if(fridgeModel.indexOf(shoppingListView.getSelectedValue()) == -1){
            fridgeModel.addElement(shoppingListView.getSelectedValue());
        }
        
        fridgeListView.setModel(fridgeModel);
    }                                              

    private void takeFromFridgebtnActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
        if(fridgeListView.getSelectedIndex() != -1){
            fridgeModel.removeElementAt(fridgeListView.getSelectedIndex());
            fridgeListView.setModel(fridgeModel); 
        }else {
            //do nothing cannot, delete from empty list
            return;
        }
    }                                                 

    private void generateShopListbtnActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
        shoppingListModel = new DefaultListModel();
        //example salad week
        mealPlanShoppingList.getText();
        //there will be some other array data here, just for debugging purposes so I can write the code
        Ingredient[] currentIngredients = DatabaseHandler.getIngredients();
        //query to get ingredients associated with salad week
        int i = 0;
        //compare
        while(i < currentIngredients.length){
           if(fridgeListView.getSelectedValuesList().indexOf(currentIngredients[i]) == -1) {
               shoppingListModel.addElement(currentIngredients[i]);
           }
           
           i++;
        }
        
        shoppingLabel.setText("The Shopping List");
        //set generated list
        shoppingListView.setModel(shoppingListModel);
    }                                                   
    */
    private void SearchGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchGoActionPerformed
        // TODO add your handling code here:
        //Take the input from textfield
        String queryInput = recipeSearchText.getText();
        
        //Pass the input into a search function
        Recipe[] resultList = DatabaseHandler.searchRecipes(queryInput);
        
        //Use the search result array to populate the list item
        DefaultListModel resultListModel = new DefaultListModel();
        for(int i = 0; i < resultList.length; i++){
            resultListModel.addElement(resultList[i].getName());
        }
        
        //display the search result
        //TODO for somereason the results are not being displayed anywhere in the
        //gui
        searchResultList.setModel(resultListModel);
        searchResultsPane.setVisible(true);
    }//GEN-LAST:event_SearchGoActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeFrame().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayOfWeekDropMenu;
    private javax.swing.JLabel InstructionsLabel;
    private javax.swing.JTabbedPane ManagerSheet;
    private javax.swing.JButton SearchGo;
    private javax.swing.JButton StoreButton;
    private javax.swing.JButton addIngredient;
    private javax.swing.JTextField addRecipeCategory;
    private javax.swing.JTextArea addRecipeInstructions;
    private javax.swing.JTextField addRecipeName;
    private javax.swing.JPanel addRecipePanel;
    private javax.swing.JButton applyButton;
    private javax.swing.JCheckBox breakfastPlannerCheckbox;
    private javax.swing.JTextField breakfastPlannerTextView;
    private javax.swing.JButton clearPlanner;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextView;
    private javax.swing.JComboBox<String> daysBox;
    private javax.swing.JTextArea debugArea;
    private javax.swing.JCheckBox dinnerPlannerCheckbox;
    private javax.swing.JTextField dinnerPlannerTextView;
    private javax.swing.JTextArea fridgeListView;
    private javax.swing.JTextField ingredientCal;
    private javax.swing.JTextField ingredientFat;
    private javax.swing.JLabel ingredientFatlab;
    private javax.swing.JTextField ingredientGroup;
    private javax.swing.JTextField ingredientName;
    private javax.swing.JTextField ingredientProtein;
    private javax.swing.JLabel ingredientProteinlab;
    private javax.swing.JTextField ingredientSodium;
    private javax.swing.JTextField ingredientSugar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JCheckBox lunchPlannerCheckbox;
    private javax.swing.JTextField lunchPlannerTextView;
    private javax.swing.JTextField mealPlanShoppingList;
    private javax.swing.ButtonGroup mealsGroup;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLoad;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JButton moveFromList;
    private javax.swing.JRadioButton radioBreakfast;
    private javax.swing.JRadioButton radioDinner;
    private javax.swing.JRadioButton radioLunch;
    private javax.swing.JTextArea recipeInstruc;
    private javax.swing.JList<String> recipeList;
    private javax.swing.JTextField recipeSearchText;
    private javax.swing.JScrollPane recipeSelectionListView;
    private javax.swing.JList<String> searchResultList;
    private javax.swing.JPanel searchResultsPane;
    private javax.swing.JTextArea shoppingListView;
    private javax.swing.JButton storeRecipe;
    private javax.swing.JTextField weekID;
    private javax.swing.JTextField weekId;
    // End of variables declaration//GEN-END:variables
}
